#!/usr/bin/env bash
# refresh-tool-index.sh — Kali Linux tool index refresh
# Equivalent to Windows version refresh-tool-index.ps1
# Output: skills/tool-index.md + skills/tool-index.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/tool-discovery.sh"

OUTPUT_MD="${1:-${SKILL_ROOT}/tool-index.md}"
OUTPUT_JSON="${2:-${SKILL_ROOT}/tool-index.json}"

GENERATED_AT=$(date '+%Y-%m-%d %H:%M:%S %z')

# ─── Generate Markdown ────────────────────────────────────────────────────────────────

{
    echo "# Reverse Engineering Tool Index"
    echo ""
    echo "- Scan Time: $GENERATED_AT"
    echo "- Scan Platform: Kali Linux ($(uname -r))"
    echo "- Routing Entry: \`SKILL.md\` → \`routing.md\` → Corresponding sub-skill"
    echo "- Note: This table is auto-generated by \`kali/scripts/refresh-tool-index.sh\` ."
    echo "- 注意: 对于 jshookmcp 这类 MCP server，\`yes\` 只表示本机具备通过 node/npx 拉起它的条件，不表示它已经在 MCP configuration里注册并启用。"
    echo ""
    echo "| Tool | Skill | Purpose | Available | Path | Version | Source | Script Refs |"
    echo "|---|---|---|---|---|---|---|---|"

    for entry in "${TOOL_CATALOG[@]}"; do
        result=$(resolve_tool "$entry")
        IFS='|' read -r name skill purpose available resolved_path version source <<< "$result"

        # Get script reference
        refs="${SCRIPT_REFS[$name]:-—}"
        refs_display="${refs//,/<br>}"

        path_display="${resolved_path:-—}"
        version_display="${version:-—}"

        echo "| $name | $skill | $purpose | $available | $path_display | $version_display | $source | $refs_display |"
    done
} > "$OUTPUT_MD"

# ─── Capability Status View ──────────────────────────────────────────────────────────────────

{
    echo ""
    echo "---"
    echo ""
    echo "## Capability Status View"
    echo ""
    echo "| Capability | Tool Available | MCP Registered | Service Online | Auto Install | Install Method |"
    echo "|------|---------|-----------|---------|-----------|---------|"

    CAPABILITY_NAMES=("jadx" "apktool" "jeb-pro" "frida" "idalib-mcp" "jshookmcp" "reqable-mcp" "anything-analyzer" "idapro" "r2" "adb" "agent-browser" "ghidra-mcp" "seclists" "proxycat" "burpsuite-mcp" "nmap" "sqlmap" "hashcat" "hydra" "gobuster" "ffuf" "msfconsole" "nuclei")

    for cap_name in "${CAPABILITY_NAMES[@]}"; do
        # Check if tool is available
        tool_available="✗"
        case "$cap_name" in
            jeb-pro)
                if command -v jeb &>/dev/null || [[ -x "$HOME/tools/JEB/jeb" ]] || [[ -x "$HOME/JEB/jeb" ]] || [[ -x "/opt/jeb/jeb" ]]; then
                    tool_available="✓"
                fi
                ;;
            reqable-mcp|jshookmcp)
                if command -v npx &>/dev/null; then tool_available="✓"; fi
                ;;
            *)
                if command -v "$cap_name" &>/dev/null; then tool_available="✓"; fi
                ;;
        esac

        # Check MCP registration status
        mcp_registered="—"
        mcp_name="$cap_name"
        case "$cap_name" in
            jshookmcp) mcp_name="jshook" ;;
        esac
        mcp_check=$(check_mcp_registered "$mcp_name")
        if [[ "$mcp_check" == "true" ]]; then
            mcp_registered="✓"
        fi

        # Check service online status
        service_online="—"
        case "$cap_name" in
            idapro)
                if test_tcp_port 13337 2>/dev/null; then service_online="✓"; fi
                ;;
            anything-analyzer)
                if test_tcp_port 23816 2>/dev/null; then service_online="✓"; fi
                ;;
            ghidra-mcp)
                if test_tcp_port 8765 2>/dev/null; then service_online="✓"; fi
                ;;
            burpsuite-mcp)
                if test_tcp_port 9876 2>/dev/null; then service_online="✓"; fi
                ;;
        esac

        # Get install method
        can_auto="✓"
        bootstrap_kind="apt-package"
        case "$cap_name" in
            jadx|ghidra-mcp|seclists)
                bootstrap_kind="github-release"
                ;;
            frida|idalib-mcp|proxycat)
                bootstrap_kind="pip-package"
                ;;
            jshookmcp|reqable-mcp|agent-browser)
                bootstrap_kind="npm-mcp"
                ;;
            jeb-pro)
                bootstrap_kind="manual"
                can_auto="✗"
                ;;
            anything-analyzer|idapro)
                bootstrap_kind="local-http-mcp"
                ;;
            burpsuite-mcp)
                bootstrap_kind="manual"
                can_auto="✗"
                ;;
        esac

        echo "| $cap_name | $tool_available | $mcp_registered | $service_online | $can_auto | $bootstrap_kind |"
    done

    echo ""
    echo "> ✓ = Yes | ✗ = No | — = N/A or not detected"
    echo ""
} >> "$OUTPUT_MD"

# ─── Generate JSON ─────────────────────────────────────────────────────────────────────

if command -v jq &>/dev/null; then
    # Use jq to generate structured JSON
    json_tools="[]"
    for entry in "${TOOL_CATALOG[@]}"; do
        result=$(resolve_tool "$entry")
        IFS='|' read -r name skill purpose available resolved_path version source <<< "$result"
        refs="${SCRIPT_REFS[$name]:-}"

        avail_bool="false"
        [[ "$available" == "yes" ]] && avail_bool="true"

        json_tools=$(echo "$json_tools" | jq \
            --arg name "$name" \
            --arg skill "$skill" \
            --arg purpose "$purpose" \
            --argjson available "$avail_bool" \
            --arg resolved_path "$resolved_path" \
            --arg version "$version" \
            --arg source "$source" \
            --arg script_refs "$refs" \
            '. + [{
                name: $name,
                skill: $skill,
                purpose: $purpose,
                available: $available,
                resolved_path: $resolved_path,
                version: $version,
                source: $source,
                script_refs: ($script_refs | split(","))
            }]')
    done

    jq -n \
        --arg generated_at "$GENERATED_AT" \
        --arg platform "kali-linux" \
        --argjson tools "$json_tools" \
        '{
            generated_at: $generated_at,
            platform: $platform,
            routing_entry: ["SKILL.md", "routing.md"],
            tools: $tools
        }' > "$OUTPUT_JSON"
else
    # Generate simple JSON when jq is not available
    echo "{\"generated_at\": \"$GENERATED_AT\", \"platform\": \"kali-linux\", \"note\": \"install jq for full JSON output\"}" > "$OUTPUT_JSON"
fi

echo "✅ Tool index refreshed"
echo "  markdown=$OUTPUT_MD"
echo "  json=$OUTPUT_JSON"
echo "  tools=${#TOOL_CATALOG[@]}"
